<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.eclipse</groupId>
    <artifactId>tacos-inventory-service</artifactId>
    <version>0.1-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>tacos-inventory-service</name>
    <description>
        This is a very simple inventory service api running in TOMCAT server.
    </description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.report.sourceEncoding>UTF-8</project.report.sourceEncoding>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
        <compiler-plugin.version>3.10.1</compiler-plugin.version>
        <war-plugin.version>3.3.2</war-plugin.version>
        <cargo.version>1.10.4</cargo.version>
    </properties>

    <dependencies>

        <!-- https://mvnrepository.com/artifact/javax/javaee-api -->
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>


        <!-- Hibernate 5.0.12 (Compatible with Java EE 7 / JPA 2.1) -->

        <!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-core -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>4.3.1.Final</version>
        </dependency>

        <!-- H2 Database for Testing (or replace with MySQL) -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>2.1.214</version>
            <scope>runtime</scope>
        </dependency>


        <dependency>
            <groupId>org.jboss.weld</groupId>
            <artifactId>weld-api</artifactId>
            <version>2.2.Final</version>  <!-- Weld 2.2.x matches WildFly 8's built-in CDI 1.1 -->
            <scope>provided</scope>
        </dependency>


    </dependencies>


    <build>
        <finalName>tacos-cloud-inventory-service</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <failOnMissingWebXml>true</failOnMissingWebXml>
                    <!--                    <outputDirectory>/opt/wildfly/standalone/deployments</outputDirectory>-->
                    <warName>tacos-inventory-service</warName>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>
